### PR TITLE
Networking UI improvements

### PR DESCRIPTION
**Pull request by glaszig**
removed some superfluous elements and styling.

| before | after |
|--------|-------|
| before | after |

### CODE REVIEW

**Comment by billz** [comment]
Nice update.

network

Along these lines, I thought about replacing the checkmarks with icons that represent the connection type (ethernet, wlan, etc). Above is a mockup with the original layout.

**Comment by glaszig** [comment]
i like those. but is do we have infrastructure to distinguish between wored and wireless?

i also have other genereal ui improvements coming in another branch.

**Comment by billz** [comment]
First thought was to simply use the interface prefix, ie., wlan*, eth*, docker*, wg* etc. 
Wouldn't match all possible interfaces but would probably cover a majority of cases.

Related discussion #849

**Comment by billz** [comment]
You might want to look at @zbchristian's pull request in the Insiders repo, which adds some new tabs to the Networking UI.

tabs

**Comment by glaszig** [comment]
i have added back the tab.

re those icons: those are in the column "internet access" which denotes reachability of routing and dns. i would rather put icons related to those there instead of the interface type. icons for the interface type should go in front of the interface name in the first column, imo.

**Pull request merged**
