### PR TITLE
Glaszig dashboard wifi design

### PR DESCRIPTION
**Pull request by billz**
Applied styles from #845 to theme files

### CODE REVIEW

**Comment by glaszig** [comment]
sorry. i always neglect the themes -.-

**Comment by billz** [comment]
I know you're a big fan of themes ^_^
would be simpler with Sass / Less but that is a project for another day... 
can you push to this branch instead? you should be a collaborator on this repo

**Comment by glaszig** [comment]
jesus. i fucked up the history of this one :(

**Comment by billz** [comment]
easy enough to squash/fixup/drop commits, but not critical

**Pull request merged**
