### PR TITLE
Adding support for flagging nohook/hoook wpa_supplicant

### PR DESCRIPTION
**Pull request by r-teller**
Created to address https://github.com/RaspAP/raspap-insiders/issues/168

Adds logic to check if the dhcp interface selected starts with "wl" or not and if so it adds conditional log to check if nohook wpa_supplicant or hook wpa_supplicant should be written to /etc/dhcpcd.conf or not

I also updated the matching logic for get_netcfg.php to not accidentally read into the next net block and interpret flags set for a different interface

Previous logic read to end of doc and so if wlan0 and wlan1 existed but wlan1 had gateway configured but it did not exist in wlan0 it would still show up

The updated logic checks now for either end of doc or # RaspAP

### CODE REVIEW

**Comment by billz** [comment]
@r-teller thanks for the PR. I'll circle back to this shortly and give it a round of testing

**Comment by r-teller** [comment]
> @r-teller thanks for the PR. I'll circle back to this shortly and give it a round of testing

I have noticed that the hostapd logic also needs to be updated so that it doesn't step on settings configured in dhcp, i am working on a fix for that as well.

**Comment by fuad00** [comment]
Should this PR fix a problem of broken AP when i switch it to wlan1?

**Comment by billz** [comment]
@r-teller thanks for the contribution. I've resolved the issues mentioned above and created a new PR.

**Pull request closed without merging**
