### PR TITLE
Add VPN provider support for AdGuard

### PR DESCRIPTION
**Pull request by billz**

### CODE REVIEW

**Comment by billz** [comment]
Resolves #1705

**Comment by easylo** [comment]
@billz , when you get the code from my fork, please specify that this code does not come from you but from @easylo  and thank me

**Comment by billz** [comment]
@easylo if you compare the two forks I believe you'll find very little of yours was actually used. It was not functional and needed significant work. That said, I'm grateful for the inspiration

**Comment by easylo** [comment]
Next time you copy and paste someone's code and translate the comments, don't forget any comments. ;) 
`// Trier les villes par ordre alphabétique`
https://github.com/RaspAP/raspap-webgui/blob/master/includes/provider.php#L305C45-L305C87

**Comment by billz** [comment]
If it will make you happy, open a PR and add comments on the specific lines you wish to be credited with

**Comment by billz** [comment]
Resolved in #1707

**Pull request merged**
