### PR TITLE
Plugin architecture to support user add-ons

### LINKED ISSUE #1692: Plugin architecture to support user add-ons
### Discussed in https://github.com/RaspAP/raspap-webgui/discussions/1052

<div type='discussions-op-text'>

<sup>Originally posted by **billz** November 13, 2021</sup>
One idea I've played with is adding plugin support for RaspAP. This would let other developers build enhancements for the project without modifying the core code. Examples include this [interesting fork](https://github.com/Erik1000/raspap-webgui/commit/ebb73e41d1929983a312367c93bc86ea139c3f78) of RaspAP that adds [RPiPlay](https://github.com/FD-/RPiPlay) integration. While this may not appeal to everyone, there are probably some users who would add this to RaspAP if it could be done simply.
</div>

### PR DESCRIPTION
**Pull request by billz**
Resolves #1692

### CODE REVIEW

**Comment by assachs** [comment]
I think "return false" is missing in PluginManager.handlePageAction

TypeError: RaspAP\Plugins\PluginManager::handlePageAction(): Return value must be of type bool, none returned
 at RaspAP.Plugins.PluginManager.handlePageAction(PluginManager.php:89)
 at require_once(page_actions.php:10)
 at (main)(index.php:116)

**Comment by assachs** [comment]
Also two Problems with sidebar:

Adblock is shown, but it's disabled:
 $this->addItem(_('Ad Blocking'), 'far fa-hand-paper', 'adblock_conf', 40,
            fn() => defined('RASPI_ADBLOCK_ENABLED') && **RASPI_HOTSPOT_ENABLED** && !$_SESSION["bridgedEnabled"]
        );

RestAPI:
 $this->addItem(_('RestAPI'), 'fas fa-puzzle-piece', 'restapi_conf', 120,
            fn() => defined('**RASPI_VNSTAT_ENABLED'**) && **RASPI_VNSTAT_ENABLED**
        );

**Comment by billz** [comment]
> I think "return false" is missing in PluginManager.handlePageAction

In testing, the PluginManager did not handle multiple plugin instances. So this is still in active development.

Will look into the sidebar issues, thanks.

**Comment by assachs** [comment]
I migrated my plugin to the new plugin architecture. Everything worked very well. Thank you for implementing it.

**Pull request merged**
