### PR TITLE
Tweak layout of dashboard client widget

### PR DESCRIPTION
**Pull request by billz**
Layout tweak of #845, aligns divs for a more compact display.

client

### CODE REVIEW

**Comment by glaszig** [comment]
can we get top and bottom of the gauge-chart line up with top of "connected to" and bottom of "frequency"? maybe remove fixed height of chart and add `.h-100` to its grid container.

(i would or will do it when i have access to my pi again).

**Comment by glaszig** [comment]
also, left edge of text should line up with heading.

**Comment by billz** [comment]
> can we get top and bottom of the gauge-chart to line up with top of "connected to" and bottom of "frequency"? 

A bit tricky due to chart.js having its own non-Bootstrap DOM element rendering. This scales the vertical height of the chart in relation to the adjacent div.

Screen Shot 2021-04-09 at 8 46 51 AM

**Comment by glaszig** [comment]
i see. don't bother, then. good enough for now.

**Pull request merged**
