### PR TITLE
RestAPI installer integrated

### LINKED ISSUE #1498: FEATURE REQUEST: Rest API for AP management
## Is your feature request related to a problem? 
No, but with the RestAPI a whole new world of automation opens, like HA integration with automation based on connected clients, etc...
## Describe the solution you'd like
A Rest API with functionality like:
- get connected clients amount
- list active clients (with details)
- Shutdown AP/ Start AP
- Get VPN status/ details
- Get Adblock status/ details

## Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by NL-TCH**
Hi,

I am creating this PR because: 
- all the GET requests are in place
- i am getting really busy next months
- i am a little burned out on this project :)

Feel free to create more post request functions etc...

Gr. TCH

*this is also tested in docker
/resolves #1498 #1507 #1372 #602 #393

### CODE REVIEW

**Comment by billz** [comment]
What's your take on the CodeQL scan results?
Should `shlex.quote()` be used to sanitize arguments when specifying `shell=True`?

**Comment by NL-TCH** [comment]
> What's your take on the CodeQL scan results? Should `shlex.quote()` be used to sanitize arguments when specifying `shell=True`?

Yeah that would sanitize the input, good for security!

**Comment by NL-TCH** [comment]
Things to do before merge:

- [ ] Sanitize input of API (shlex.quote())
- [ ] Create documentation

Things to improve after merge:

- [ ] Add "insider" tags for paths like firewall and ddns
- [ ] Put more paths behind auth module for secret info (like /ap that contains the wifi password) (maybe everything has to be put behind auth for overall security)
- [ ] Add more POST functions, for DDNS, DHCP, DNS
- [ ] Add docker option `--rest 1` to auto install api on docker install
- [ ] Expose port 8081 in dockerfile for external API access

**Comment by NL-TCH** [comment]
@billz checks now pass, everything is placed behind api auth, and post calls are removed.
can you provide the documentation?

**Comment by billz** [comment]
> can you provide the documentation + gui part for enabling, disabling and setting the api key?

@NL-TCH absolutely! this is the least I can do 😅 excellent work in this PR

**Comment by billz** [comment]
Using `vlucas/phpdotenv` to read/write API key from `.env`. Requires some extra dependencies, but nothing too overly burdensome.

**Comment by billz** [comment]
On second thought, the extra dependencies were overkill just to read/set an .env file. Created a simple class instead.

**Comment by billz** [comment]
Basic web UI is essentially done. Next up: test a clean install of the feature branch.

**Comment by billz** [comment]
Ran through a clean install on a fresh OS:
`curl -sL https://install.raspap.com | bash -s -- --repo NL-TCH/raspap-webgui --branch REST-API`

After a reboot, started the `restapi.service`. Status check points to an issue with fastapi and/or dependencies:

```
$ sudo systemctl status restapi.service
● restapi.service - raspap-restapi
     Loaded: loaded (/lib/systemd/system/restapi.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-03-06 18:53:04 CET; 1s ago
    Process: 1847 ExecStart=/usr/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8081 (code=exited, status=1/FAILURE)
```
```
$ journalctl -xe
Mar 06 18:54:13 raspberrypi python3[1870]: /usr/bin/python3: No module named uvicorn
```
```
$ python3 -m site --user-site
/home/pi/.local/lib/python3.11/site-packages
```

Assume this is venv related? Tried `export PATH=$PATH:$HOME/.local/bin` with same result. 
Possible fix? `python -m uvicorn main:app --reload` ([source](https://stackoverflow.com/questions/59025891/uvicorn-is-not-working-when-called-from-the-terminal))

Everything else is looking good, just need to get over this hurdle.

**Comment by billz** [comment]
Got it working.

1. The restapi.service file specified `User=root` while the python modules are installed under the current user. 
2. Adding dotenv as a dependency permitting reading of `.env` file.
3. `main.py` raised exceptions with each `@app.get ... api_key`. Fixed these (version related?)
4. Opted to move, rather than copy, /api to /etc/raspap to reduce confusion for users.

Service loads and API is fully functional. Some minor work left on the UI side to read/set API key.

**Comment by billz** [comment]
Appears my fixes raised some new CodeQL vulnerabilities 🤔

**Comment by billz** [comment]
@NL-TCH feature branch installs cleanly 🎉 

restapi-settings

With the last commits I think we're good to merge.

**Comment by billz** [comment]
@NL-TCH doc link is fastapi's autogenerated docs at [host]:8081/docs. This could probably be clarified.

you took the lead on this, so kudos is all yours :)

**Comment by NL-TCH** [comment]
> @NL-TCH doc link is fastapi's autogenerated docs at [host]:8081/docs. This could probably be clarified.
> 
> you took the lead on this, so kudos is all yours :)

Smart! yeah that might be self explanatory
I'm down to merge 🥳

**Pull request merged**
