### PR TITLE
Adds minimal SD card write support to installer

### PR DESCRIPTION
**Pull request by billz**
Essentially wraps @zbchristian's [contribution](https://github.com/RaspAP/raspap-tools/blob/main/raspian_min_write.sh)  and integrates it into the Quick Installer.

### CODE REVIEW

**Comment by billz** [comment]
Resolves #306

**Comment by billz** [comment]
### Filesytem 
```
$ cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=bc6a318f-01  /boot           vfat    defaults          0       2
PARTUUID=bc6a318f-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
tmpfs /tmp tmpfs  nosuid,nodev 0 0
tmpfs /var/log tmpfs  nosuid,nodev 0 0
tmpfs /var/tmp tmpfs  nosuid,nodev 0 0
tmpfs /var/lib/misc tmpfs  nosuid,nodev 0 0
tmpfs /var/cache tmpfs  nosuid,nodev 0 0
tmpfs /var/lib/vnstat tmpfs  nosuid,nodev 0 0
tmpfs /var/php/sessions tmpfs  nosuid,nodev 0 0
```
###  Memory use
`free -m | awk '/Mem:/ { total=$2 ; used=$3 } END { print used/total*100}'`

pre minwrite %
11.8812 

post minwrite %
29.703

### Disk I/O

```
$ sudo iotop -aoP

Total DISK READ:         0.00 B/s | Total DISK WRITE:         0.00 B/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:       0.00 B/s
    PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                                                                                              
    101 ?sys root          0.00 B      8.00 K  ?unavailable?  [jbd2/mmcblk0p2-8]
    837 ?sys www-data     24.00 K      0.00 B  ?unavailable?  lighttpd -D -f /etc/lighttpd/lighttpd.conf
    890 ?sys www-data    800.00 K      0.00 B  ?unavailable?  php-cgi
    891 ?sys www-data      4.00 K      0.00 B  ?unavailable?  php-cgi
    892 ?sys www-data      4.00 K      0.00 B  ?unavailable?  php-cgi
    893 ?sys www-data     80.00 K      0.00 B  ?unavailable?  php-cgi
```

**Review by zbchristian — COMMENTED** [review]
@billz The implemenation look good to me, but I have currently no chance to test it (on vacation right now), but could do it next week.

Some comments wrt minwrite.sh: 
- I am not sure, why `triggerhappy` is uninstalled (function `_remove_packages`). I assume its just a relict from my investigation of read-only systems. Likely not needed here, since we assume a headless system.
- I assume you checked, that the all the disabled services (function `_disable_services`) are actually existing. In principle I would opt to ignore a not existing services. 
- Concerning to disable the service `console-setup`: this again might not be needed here. Makes sense for read-only systems.

**Comment by billz** [comment]
@zbchristian many thanks for the feedback. enjoy your holiday :)

**Pull request merged**
