### PR TITLE
Routing custom install dir bugfix

### LINKED ISSUE #803: Custom install directory not working
**Before submitting an issue**

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ and Wiki before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Normal installation (curl -sL https://install.raspap.com | bash), I changed only the directory where the webgui will be installed.

**Your environment**

RASPAP_LATEST=2.6.1

root@Galactus:/var/www/html# uname -a
Linux Galactus 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
root@Galactus:/var/www/html# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

[snip] @billz removed installer output

I think the problem is the fact that 50-raspap-router.conf  is not updated with custom install directory, something like:

$HTTP["url"] =~ "^/(?!(dist|app|ajax|config)).*" ==> $HTTP["url"] =~ "^$webroot_dir/(?!(dist|app|ajax|config)).*"

After this change the interface it is accesible, but only the main page. Any item in menu gives 404 error. In lighttpd log (after enabling accesslog) I can see the following:

2021-02-11 21:01:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  parse_ini_file(/etc/raspap/hostapd.ini): failed to open stream: No such file or directory in /var/www/html/thanos/includes/wifi_functions.php on line 145
2021-02-11 21:01:56: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  parse_ini_file(/etc/raspap/hostapd.ini): failed to open stream: No such file or directory in /var/www/html/thanos/includes/dashboard.php on line 182

I remember that in previous versions there was an hostapd.ini, not .conf.

Please accept my sincere apologies in advance if I should open another bug report for the following issue, but i will describe it here because this one is easy.

Another problem observed for a long time (at least 1 year) (i didn't followed the versions and/or diff them) is the fact that **session.cookie_httponly** it is not changed by installer, see below:

root@Galactus:/var/www/html# sed -i -E 's/^session\.cookie_httponly\s*=\s*(0|([O|o]ff)|([F|f]alse)|([N|n]o))\s*$/session.cookie_httponly = 1/' /etc/php/7.3/cgi/php.ini
root@Galactus:/var/www/html# grep session.cookie_httponly /etc/php/7.3/cgi/php.ini 
session.cookie_httponly =
root@Galactus:/var/www/html# 

I am not a regex expert, but my solution for this one is:

sed -i 's/session.cookie_httponly =/session.cookie_httponly = 1/g' /etc/php/7.3/cgi/php.ini

Simple.

Thank you.

### PR DESCRIPTION
**Pull request by billz**
Cherry picked from #749 for clarity. Resolves #803

### CODE REVIEW

**Comment by billz** [comment]
Ran through an install with this branch, specifying "/var/www/html/custom" as the install directory. 
50-raspap-router.conf is rewritten by the installer, like so:

``` 
$HTTP["url"] =~ "^/custom/(?!(dist|app|ajax|config)).*" {
      url.rewrite-once = ( "^/custom/(.*?)(\?.+)?$"=>"/custom/index.php/$1?$2" )
      server.error-handler-404 = "/custom/index.php"
  }
```

With lighttpd `debug.log-condition-handling` enabled, I captured a request for /custom/openvpn_conf:

```
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.449) HTTP["url"] ( /custom/index.php/openvpn_conf ) compare to  ^/custom/(?!(dist|app|ajax|config)).* 
(configfile-glue.c.493) 2 (uncached) result: true 
(response.c.435) -- splitting Request-URI 
(response.c.436) Request-URI     :  /custom/index.php/openvpn_conf? 
(response.c.437) URI-scheme      :  http 
(response.c.438) URI-authority   :  raspberrypi.local 
(response.c.439) URI-path (raw)  :  /custom/index.php/openvpn_conf 
(response.c.440) URI-path (clean):  /custom/index.php/openvpn_conf 
(response.c.441) URI-query       :   
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(mod_access.c.177) -- mod_access_uri_handler called 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(response.c.586) -- before doc_root 
(response.c.587) Doc-Root     : /var/www/html 
(response.c.588) Rel-Path     : /custom/index.php/openvpn_conf 
(response.c.589) Path         :  
(response.c.631) -- after doc_root 
(response.c.632) Doc-Root     : /var/www/html 
(response.c.633) Rel-Path     : /custom/index.php/openvpn_conf 
(response.c.634) Path         : /var/www/html/custom/index.php/openvpn_conf 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 1 (cached) result: false 
(configfile-glue.c.581) === start of condition block === 
(configfile-glue.c.500) 2 (cached) result: true 
(response.c.658) -- logical -> physical 
(response.c.659) Doc-Root     : /var/www/html 
(response.c.660) Basedir      : /var/www/html 
(response.c.661) Rel-Path     : /custom/index.php/openvpn_conf 
(response.c.662) Path         : /var/www/html/custom/index.php/openvpn_conf 
(response.c.674) -- handling physical path 
(response.c.675) Path         : /var/www/html/custom/index.php/openvpn_conf 
(response.c.682) -- handling subrequest 
(response.c.683) Path         : /var/www/html/custom/index.php 
(response.c.684) URI          : /custom/index.php 
(response.c.685) Pathinfo     : /openvpn_conf
```

Appears to be ok. However, the problem is that `$_SERVER['REQUEST_URI']` in index.php is `/custom/openvpn_conf` so the routing action handler fails and the default dashboard view is loaded. 

The solution is to either rewrite this or isolate the path (eg., `/openvpn_conf`) in index.php.

**Comment by billz** [comment]
lighttpd's mod_fastcgi supports `PATH_INFO` as described [here](https://tools.ietf.org/html/rfc3875#section-4.1.5), so 74497be resolves this. 
Needs testing.

**Comment by mp035** [comment]
Hi Bill, why does the requested path have index.php in it :
`(configfile-glue.c.449) HTTP["url"] ( /custom/index.php/openvpn_conf )`
It looks to me like whichever link you clicked to get this log has been incorrectly translated (probably by me, sorry).  The best solution would be to fix the link.

**Comment by mp035** [comment]
Hi Bill,  does this happen with every path?   I tested all the pages and had no issues but I was using my routing_and_blade branch so I am wondering if the hrefs differ between branches?

**Comment by billz** [comment]
Hi Mark, appears to be the case with every path. hrefs are identical between branches. openvpn_conf is just the test case I used; other request-URIs have the same results. Your rewrite fix + the update to `$_SERVER['PATH_INFO']` seems to do the trick.

Did a clean install with this branch and tested ok.

**Comment by mp035** [comment]
Hi Bill,  this is likely because your branch doesn't use the changes to implement blade.  When the blade templates are compiled, the hrefs will be translated.  Is there any chance you could test mp035/routing_and_blade (just replace /var/www/custom with the repo, there should be no need to re-run the installer) and see if the issue persists?

I only suggest this because you may be chasing your tail on this one.  Without the services provided by blade other areas (form submission etc etc etc) may start to show similar issues.

**Comment by mp035** [comment]
I just remembered, the installer will need to be run too.  It adds the blade repository to the pi.

**Comment by mp035** [comment]
Please ignore my comments like the ramblings of a crazy person!  I am working on a project with a PI in it so I re-tested my fix.  You are correct @billz, your fix should do it.  It has nothing to do with blade.  My testing was flawed.

**Comment by billz** [comment]
@mp035 no worries, Mark :) I may have complicated things by separating routing from blade in your original PR.

**Pull request merged**
