### PR TITLE
Wifi stations UI

### PR DESCRIPTION
**Pull request by glaszig**
the wifi stations ui currently is a mixed bag of everything: connected, known and nearby stations. this recently drove me nuts.

so i made it look like this:

Bildschirmfoto 2021-05-30 an 22 09 17

### CODE REVIEW

**Comment by billz** [comment]
@glaszig nicely done. it truly is a mixed bag. this brings some much needed sanity to the UI.

**Comment by billz** [comment]
As I recall, there was a lot of experimentation to get these cards to align/collapse, etc. predictably at different screen resolutions. Looks like we've lost either a div or the left padding and the grid spacing is uneven. Otherwise works well.


no left margin or missing div (feature branch):
margin-feature

left margin (master):
margin-master

even grid layout (master):
grid-master

uneven grid layout (feature):
grid-feature

**Comment by glaszig** [comment]
fixed, i think. grid layout is a pita unless you use... css grid spec :)
also fixed a little class issue, making the heading and rescan button line up vertically.

| desktop | mobile |
|--------|-------|
| desktop | mobile |

**Comment by glaszig** [comment]
rebased on master as well, sorry. i just love rebasing -.-

**Comment by billz** [comment]
> fixed, i think. grid layout is a pita unless you use... css grid spec :)

looks good now, thanks. agreed that bootstrap grid is often a pita

> rebased on master as well, sorry. i just love rebasing -.-

yes I've noticed ;)

**Comment by billz** [comment]
New strings need to be added to en_US locale. It's non critical so I'll do this post-merge

**Pull request merged**
