### PR TITLE
Input sanitization for wpa client, Fix for #1325

### PR DESCRIPTION
**Pull request by eldstal**
I'm not familiar enough with `wpa_supplicant`, but if the intended network ID is always numerical, I would recommend also adding a check for `isnumeric()` of the `$_POST` parameter for a little bit of extra constraint.

### CODE REVIEW

**Comment by billz** [comment]
@eldstal thanks for the PR. network ID is an integer so agreed adding `is_numeric()` would be prudent here.

**Comment by eldstal** [comment]
There, a more robust check is in place, and this should resolve the last part of #1325

**Comment by billz** [comment]
Excellent, thanks. Resolves #1325

**Comment by billz** [comment]
Unfortunately this introduces a new bug. `escapeshellarg()` wraps $netid with single quotes, thus causing it to fail the is_numeric check. I also believe wpa_cli expects integer values.

I missed this in testing, will open a new PR.

**Pull request merged**
