### PR TITLE
Custom VPN provider support

### LINKED ISSUE #1414: Custom VPN set up
## Is your feature request related to a problem? 
There are a lot of new VPN products coming to market
ProtonVPN is now available
Wireguard
Lightway
etc

## Describe the solution you'd like
Plug in CLI config to use *ANY* of them
For example, for basic functions like connect, status, disconnect, create a cli config page
Path to executable:
executable name:
command to connect:
command to disconnect:
command to turn on logs:
command to check status:
Frequency to check status: ___ seconds
custom command if disconnected:
custom command when connect:
block traffic if connection lost/error:
email if disconnect: y/n
config file location:
custom options:
install url download:

## Describe alternatives you've considered
This may simplify administration of RASPAP - offer user options to pick a known type (wireguard, openvpn, etc) and prompt user for normal parms, but this would allow new CLI connect for new vpn software.

### PR DESCRIPTION
**Pull request by billz**
Work in progress. Resolves #1414

### CODE REVIEW

**Comment by frankoz95967943** [comment]
Wow - very nice - one addition - most of these VPN providers allow for parameter on connect to specify the country to connect to.  Ie expressvpn connect US 
ProtonVPN same
as is nord

They also have in all their CLI the ability to list country to connect to.  I do think most also have provision to connect to "best" if no option given?

expressvpn list 

will list all countries to connect to

**Comment by billz** [comment]
@frankoz95967943 yup, exactly re: country support. this first stab looks to handle basic connect / disconnect and status operations for each of these CLIs. login / logout and ability to select a country are up next.

**Comment by billz** [comment]
Progress. Testing with other providers is up next.

vpn-status

**Comment by billz** [comment]
@frankoz95967943 ExpressVPN lightway with detailed diagnostics

expressvpn-lightway

**Pull request merged**
